wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("newpage", views.newpage, name="newpage"),
    path("edit", views.edit, name="edit"),
    path("save_edit", views.save_edit, name="save_edit"),
    path("rand", views.rand, name="rand")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import markdown
import random

from . import util

class NewPageForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"rows":"5"}))

def convert_md_to_html(title):
    content = util.get_entry(title)
    markdowner = markdown.Markdown()
    if content == None:
        return None
    else:
        return markdowner.convert(content)

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry):
    html_content = convert_md_to_html(entry)
    if entry.lower() not in util.list_entries():

        request.session["entries"] = []
        for page in util.list_entries():
            if entry.lower() in page.lower():
                request.session["entries"] += [page]

        if len(request.session["entries"]) > 0:
            return render(request, "encyclopedia/substring.html", {
                "entry": entry,
                "entries": request.session["entries"]
            })
        else:
            return render(request, "encyclopedia/error.html", {
                "entry": entry
            })
    else:
        return render(request, "encyclopedia/entry.html", {
            "entry": html_content,
            "title": entry
        })

def search(request):
    search_post = request.GET.get('q', '')
    return entry(request, search_post)

def newpage(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title.lower() not in util.list_entries():
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:entry", kwargs={"entry": title}))
            else: 
                return render(request, "encyclopedia/newpage.html", {
                    "exist": True,
                    "title": title,
                    "form": form
                })
        else:
            return render(request, "encyclopedia/newpage.html", {
                "exist": False,
                "form": form
            })
    return render(request, "encyclopedia/newpage.html", {
        "form": NewPageForm
    })

def edit(request):
    if request.method == 'POST':
        title = request.POST["entry_title"]
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": request.POST["entry_title"],
            "content": content,
        })

def save_edit(request):
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        util.save_entry(title, content)
        html_content = convert_md_to_html(title)
        return render(request, "encyclopedia/entry.html", {
            "entry": html_content,
            "title": entry
        })

def rand(request):
    allEntries = util.list_entries()
    randomEntry = random.choice(allEntries)
    html_content = convert_md_to_html(randomEntry)
    return render(request, "encyclopedia/entry.html", {
        "title": randomEntry,
        "entry": html_content
    })

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>

    <form action="{% url 'encyclopedia:save_edit' %}" method="POST">
        {% csrf_token %}
        <label>Title:</label>
        <input type="text" name="title" placeholder="Title" value="{{ title }}">
        <br>
        <label>Markdown Content:</label>
        <br>
        <textarea name="content">{{content}}</textarea>
        <br>
        <input type="submit" value="Edit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    {{ entry | safe}}
    
    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{title}}">
        <input type="submit" value="Edit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    {{ entry }} page doesn't exist!

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search'%}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:rand' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Create new page</h1>

    {% if exist %}
        <p>
            The <a href="wiki/{{title}}">{{title}}</a> page already exist!
        </p>
    {% endif %}

    <form action="{% url 'encyclopedia:newpage' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/substring.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{entry}} page doesn't exist!</h1>
    <h3>Did you mean some of these below?</h3>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}